scannerStartLocation:
  ==: org.bukkit.Location
  world: world
  x: -8
  y: 101
  z: -4
  pitch: 0.0
  yaw: 0.0

scannerEndLocation:
  ==: org.bukkit.Location
  world: world
  x: 8
  y: 102
  z: 4
  pitch: 0.0
  yaw: 0.0